# Generated by Django 5.2.4 on 2025-07-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='city',
        ),
    ]
